# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main
stages:
- stage: Build
  jobs:
  - job: Build

    pool:
      vmImage: 'windows-latest'

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    # - task: VSBuild@1 t
    #   inputs:
    #     solution: '$(solution)'
    #     msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    #     platform: '$(buildPlatform)'
    #     configuration: '$(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Build SlankaToys.sln'
      inputs:
        command: 'build'
        projects: 'SlankaToys.sln'

    # - task: DotNetCoreCLI@2
    #   displayName: 'Run unit tests'
    #   inputs:
    #     command: test
    #     projects: '**/*Tests/*.csproj'
    #     arguments: '--configuration $(buildConfiguration)'

    # - task: DotNetCoreCLI@2
    #   displayName: 'New manifest for tool'
    #   inputs:
    #     command: custom
    #     custom: 'new '
    #     arguments: tool-manifest

    # - task: DotNetCoreCLI@2
    #   displayName: 'Install EF tool'
    #   inputs:
    #     command: custom
    #     custom: 'tool '
    #     arguments: install dotnet-ef

    # - task: PowerShell@2
    #   displayName: 'Generate SQL Scripts'
    #   inputs:
    #     filePath: 'generate-migrations.ps1'
    #     arguments: '-MigrationsDirectory "SlankaToys.Infrastructure/Migrations/"'

    # - task: CopyFiles@2
    #   displayName: 'Copy Pipeline Scripts'
    #   inputs:
    #     SourceFolder: 'pipelines/scripts/'
    #     Contents: '*'
    #     TargetFolder: '$(Build.ArtifactStagingDirectory)/scripts/'

    # - task: DotNetCoreCLI@2
    #   displayName: 'Publish API'
    #   inputs:
    #     command: 'publish'
    #     Arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    #     projects: 'SlankaToys.API/SlankaToys.API.csproj'
    #     publishWebProjects: false,
    #     zipAfterPublish: true

    - task: DotNetCoreCLI@2
      displayName: 'Publish UI'
      inputs:
        command: 'publish'
        Arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        projects: 'SlankaToys.UX/SlankaToys.UX.csproj'
        publishWebProjects: false,
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish build artifacts'
      inputs:
        PathToPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'STAPI'
        publishLocation: 'Container'

# - stage: Deploy
  # jobs:
  # - job: Deploy
  #   pool:
  #     vmImage: 'windows-latest'
  #   steps:
  #     # - task: PowerShell@2
  #     #   displayName: 'Run migrations'
  #     #   inputs: 
  #     #     targetType: 'inline'
  #     #     script: |
  #     #       dotnet ef database update --project $(Build.SourceDirectory)/_STAPI

  #     - task: DownloadBuildArtifacts@0
  #       displayName: 'Download build artifacts'
  #       inputs:
  #         buildType: 'current'
  #         artifactName: 'STAPI'
  #         downloadType: 'single'
  #         downloadPath: '$(System.ArtifactsDirectory)/_STAPI'

  #     # - task: AzureRmWebAppDeployment@4
  #     #   displayName: 'Deploy API'
  #     #   inputs:
  #     #     ConnectionType: 'AzureRM'
  #     #     azureSubscription: 'Azure subscription 1(c6cd04b9-627d-4ddb-811e-5278f525e468)'
  #     #     appType: 'webApp'
  #     #     WebAppName: 'slankatoys'
  #     #     packageForLinux: '$(System.ArtifactsDirectory)/_STAPI/STAPI/SlankaToys.API.zip'

  #     - task: AzureRmWebAppDeployment@4
  #       displayName: 'Deploy UI'
  #       inputs:
  #         ConnectionType: 'AzureRM'
  #         azureSubscription: 'Azure subscription 1(c6cd04b9-627d-4ddb-811e-5278f525e468)'
  #         appType: 'webApp'
  #         WebAppName: 'slankatoys-ui'
  #         packageForLinux: '$(System.ArtifactsDirectory)/_STAPI/STAPI/SlankaToys.UX.zip'

